apiVersion: v1
kind: Service
metadata:
  name: {{ include "spark-api.fullname" . }}-svc
  labels:
  {{- include "spark-api.labels" . | nindent 4 }}
spec:
  type: {{ .Values.api.type }}
  selector:
    app: sparkapi
  {{- include "spark-api.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.api.ports | toYaml | nindent 2 -}}